### ISSUE TITLE
Failed to load the atom-jshint package

### ISSUE THREAD

**Issue by badgerfan3** [Joezo/atom-jshint#104]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.201.0
**System**: Microsoft Windows 8.1
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v2.0.0

### Stack Trace

Failed to load the atom-jshint package

```
At Cannot find module 'jquery'

Error: Cannot find module 'jquery'
  at Module._resolveFilename (module.js:328:15)
  at Function.Module._resolveFilename (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\module-cache.js:383:52)
  at Function.Module._load (module.js:270:25)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at C:\Users\Caleb\.atom\packages\atom-jshint\lib\atom-jshint.js:17:11
  at Object.<anonymous> (C:\Users\Caleb\.atom\packages\atom-jshint\lib\atom-jshint.js:262:3)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Object.<anonymous> (C:\Users\Caleb\.atom\packages\atom-jshint\index.js:1:80)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at Package.module.exports.Package.requireMainModule (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\package.js:709:34)
  at C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\package.js:186:28
  at Package.module.exports.Package.measure (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\package.js:163:15)
  at Package.module.exports.Package.load (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\package.js:177:12)
  at PackageManager.module.exports.PackageManager.loadPackage (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\package-manager.js:355:14)
  at PackageManager.module.exports.PackageManager.loadPackages (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\package-manager.js:325:14)
  at Atom.module.exports.Atom.startEditorWindow (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\atom.js:633:21)
  at Object.<anonymous> (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\window-bootstrap.js:12:8)
  at Object.<anonymous> (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\window-bootstrap.js:23:4)
  at Module._compile (module.js:452:26)
  at Object.loadFile [as .js] (C:\Users\Caleb\AppData\Local\atom\app-0.201.0\resources\app.asar\src\babel.js:162:21)
  at Module.load (module.js:347:32)
  at Function.Module._load (module.js:302:12)
  at Module.require (module.js:357:17)
  at require (module.js:376:17)
  at setupWindow (file:///C:/Users/Caleb/AppData/Local/atom/app-0.201.0/resources/app.asar/static/index.js:91:23)
  at window.onload (file:///C:/Users/Caleb/AppData/Local/atom/app-0.201.0/resources/app.asar/static/index.js:32:7)

```

### Commands

```
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-achievements, v0.7.2
atom-auto-update-packages, v0.2.2
atom-jshint, v2.0.0
atom-spotify, v1.2.0
autocomplete-plus, v2.17.1
color-picker, v1.7.0
emmet-atom, v2.3.10
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by alsoicode** [comment]
Seeing the same issue on a new install in Windows 8.1 Pro
