### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by tara-marchand** [Joezo/atom-jshint#112]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.2
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v2.0.0

### Stack Trace

Uncaught Error: channel closed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:774

Error: channel closed
    at ChildProcess.target.send (child_process.js:396:26)
    at AtomJsHint.module.exports.AtomJsHint.run (/Users/taram/.atom/packages/atom-jshint/lib/atom-jshint.js:105:21)
    at AtomJsHint.<anonymous> (/Users/taram/.atom/packages/atom-jshint/lib/atom-jshint.js:71:16)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:996:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:978:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:579:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:535:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:518:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:592:35)
```

### Commands

```
     -1:13.6.0 core:paste (atom-text-editor.editor.is-focused)
     -1:09.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:09.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
  3x -1:06.2.0 core:backspace (atom-text-editor.editor.is-focused)
     -1:02.7.0 autocomplete-plus:cancel (atom-text-editor.editor.is-focused.autocomplete-active)
 51x -1:00.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:56.5.0 core:move-right (atom-text-editor.editor.is-focused)
 40x -0:55.2.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:49.3.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:48.2.0 core:save (atom-text-editor.editor.is-focused)
     -0:35.7.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused)
     -0:35.7.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:32.2.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:32.2.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:30.6.0 core:move-right (atom-text-editor.editor.is-focused.autocomplete-active)
  4x -0:29.3.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "audioBeep": false
  },
  "atom-jshint": {
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v2.0.0
emmet, v2.3.12
javascript-snippets, v1.0.0
language-freemarker, v0.2.0

# Dev
No dev packages
```

**Comment by edmundito** [comment]
Seeing this very frequently with atom v1.0.11 and atom-jshint v2.0.0.
