### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by kristianmandrup** [Joezo/atom-jshint#116]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.0.11
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v2.0.0

### Stack Trace

Uncaught Error: channel closed

```
At events.js:141

Error: channel closed
    at ChildProcess.target.send (child_process.js:396:26)
    at AtomJsHint.module.exports.AtomJsHint.run (/Users/kristianmandrup/.atom/packages/atom-jshint/lib/atom-jshint.js:105:21)
    at AtomJsHint.<anonymous> (/Users/kristianmandrup/.atom/packages/atom-jshint/lib/atom-jshint.js:66:16)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:82:11)
    at /Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1263:25
```

### Commands

```
     -0:46.2.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.is-focused)
     -0:44.9.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:44.5.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:44 core:move-to-bottom (atom-text-editor.editor.is-focused)
     -0:40.4.0 editor:select-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:40 core:cut (atom-text-editor.editor.is-focused)
  2x -0:39.8.0 core:move-up (atom-text-editor.editor.is-focused)
     -0:39.4.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:39.4.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:39.4.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:38.9.0 core:paste (atom-text-editor.editor.is-focused)
  2x -0:37.1.0 core:move-down (atom-text-editor.editor.is-focused)
     -0:36.1.0 editor:move-to-first-character-of-line (atom-text-editor.editor.is-focused)
     -0:35.9.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:35.6.0 core:save (atom-text-editor.editor.is-focused)
  7x -0:30.5.0 core:close (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "optional-jshint",
      "jshint"
    ]
  }
}
```

### Installed Packages

```coffee
# User
.bin, vundefined
Stylus, v1.0.0
atom-beautify, v0.28.7
atom-jade, v0.3.0
atom-jshint, v2.0.0
atom-typescript, v5.2.3
change-tabs, v0.2.0
color-picker, v2.0.11
color-tabs, v0.1.8
file-type-icons, v0.7.3
foldername-tabs, v0.1.5
jade-snippets, v0.5.0
language-marko, v0.4.16
linter, v1.2.4
markdown-format, v2.5.1
markdown-table-formatter, v2.5.2
new-file-plus, v0.2.1
pigments, v0.9.3
semantic-ui, v1.0.5
smart-tab-name, v1.0.3
tidy-tabs, v0.2.0
travis-ci-status, v0.18.0
zentabs, v0.8.6

# Dev
No dev packages
```

**Comment by jwhitmarsh** [comment]
I get this every time I use `typeof`

**Comment by iongion** [comment]
Me too, I get it everytime ... I cannot reproduce, it is now because of clicking the tabs.
This issue started showing when editing a file with more than 340 lines - it originally had errors in it, but then the hinter borked up, the hints that do not refer to the current content of the file, but a previous one(which one I do not know).

**Comment by jwhitmarsh** [comment]
I've had to disable the package until this is resolved. Is there anything that the maintainers need to help get this resolved?

**Comment by jwhitmarsh** [comment]
https://github.com/sindresorhus/atom-jshint

**Comment by seminice** [comment]
.............
