### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by carmelolg** [Joezo/atom-jshint#117]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v2.0.0

### Stack Trace

Uncaught Error: channel closed

```
At events.js:141

Error: channel closed
  at ChildProcess.target.send (internal/child_process.js:483:26)
  at AtomJsHint.module.exports.AtomJsHint.run (C:\Users\AUDACIASRL-clagamba\.atom\packages\atom-jshint\lib\atom-jshint.js:105:21)
  at AtomJsHint.<anonymous> (C:\Users\AUDACIASRL-clagamba\.atom\packages\atom-jshint\lib\atom-jshint.js:66:16)
  at Emitter.module.exports.Emitter.emit (C:\Users\AUDACIASRL-clagamba\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
  at C:\Users\AUDACIASRL-clagamba\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1276:25

```

### Commands

```
  2x -0:39 core:move-down (atom-text-editor.editor.is-focused)
     -0:38.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:38.3.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:38.3.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:38.3.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:38.1.0 snippets:next-tab-stop (atom-text-editor.editor.is-focused)
     -0:38.1.0 snippets:expand (atom-text-editor.editor.is-focused)
     -0:38.1.0 editor:indent (atom-text-editor.editor.is-focused)
     -0:37.6.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:36.9.0 autocomplete-plus:confirm (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:36.9.0 snippets:expand (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:35.2.0 core:backspace (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:34 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -0:20.1.0 editor:toggle-line-comments (atom-text-editor.editor.is-focused)
     -0:20 core:save (atom-text-editor.editor.is-focused)
  8x -0:04.1.0 core:backspace (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "build"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
angularjs-snippets, v0.10.18
atom-beautify, v0.28.16
atom-jshint, v2.0.0

# Dev
No dev packages
```

**Comment by kylebradshaw** [comment]
+1

**Comment by dbortoluzzi** [comment]
+1
