### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by carmelolg** [Joezo/atom-jshint#118]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.1.0
**System**: Unknown Windows Version
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v2.0.0

### Stack Trace

Uncaught Error: channel closed

```
At events.js:141

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:483:26)
    at AtomJsHint.module.exports.AtomJsHint.run (C:\Users\AUDACIASRL-clagamba\.atom\packages\atom-jshint\lib\atom-jshint.js:105:21)
    at AtomJsHint.<anonymous> (C:\Users\AUDACIASRL-clagamba\.atom\packages\atom-jshint\lib\atom-jshint.js:66:16)
    at Emitter.module.exports.Emitter.emit (C:\Users\AUDACIASRL-clagamba\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\AUDACIASRL-clagamba\AppData\Local\atom\app-1.1.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1276:25
```

### Commands

```
 16x -0:52.7.0 editor:move-line-down (atom-text-editor.editor.is-focused)
     -0:45.2.0 editor:indent-selected-rows (atom-text-editor.editor.is-focused)
     -0:45.1.0 core:save (atom-text-editor.editor.is-focused)
  2x -0:39 core:move-down (atom-text-editor.editor.is-focused)
  3x -0:38.1.0 core:select-up (atom-text-editor.editor.is-focused)
     -0:37.6.0 core:select-left (atom-text-editor.editor.is-focused)
     -0:37.3.0 core:select-down (atom-text-editor.editor.is-focused)
  3x -0:37.2.0 core:select-left (atom-text-editor.editor.is-focused)
  5x -0:36.4.0 core:backspace (atom-text-editor.editor.is-focused)
     -0:35 core:save (atom-text-editor.editor.is-focused)
     -0:27.8.0 editor:move-to-end-of-word (atom-text-editor.editor.is-focused)
     -0:22.3.0 core:copy (atom-text-editor.editor.is-focused)
  4x -0:21.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:18.5.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.3.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:02.9.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "build"
    ]
  }
}
```

### Installed Packages

```coffee
# User
angularjs, v0.3.3
angularjs-snippets, v0.10.18
atom-beautify, v0.28.16
atom-jshint, v2.0.0

# Dev
No dev packages
```

**Comment by xdumaine** [comment]
+1 this is killing me
