### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by gdmerm** [Joezo/atom-jshint#119]
[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 1.2.0
**System**: Mac OS X 10.10.5
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v2.0.0

### Stack Trace

Uncaught Error: channel closed

```
At /Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:825

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:509:16)
    at AtomJsHint.module.exports.AtomJsHint.run (/Users/gm/.atom/packages/atom-jshint/lib/atom-jshint.js:105:21)
    at AtomJsHint.<anonymous> (/Users/gm/.atom/packages/atom-jshint/lib/atom-jshint.js:71:16)
    at Emitter.module.exports.Emitter.emit (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/event-kit/lib/emitter.js:86:11)
    at TextBuffer.module.exports.TextBuffer.saveAs (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1035:20)
    at TextBuffer.module.exports.TextBuffer.save (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/text-buffer/lib/text-buffer.js:1002:19)
    at TextEditor.module.exports.TextEditor.save (/Applications/Atom.app/Contents/Resources/app.asar/src/text-editor.js:557:26)
    at Pane.module.exports.Pane.saveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:530:18)
    at Pane.module.exports.Pane.saveActiveItem (/Applications/Atom.app/Contents/Resources/app.asar/src/pane.js:513:19)
    at Workspace.module.exports.Workspace.saveActivePaneItem (/Applications/Atom.app/Contents/Resources/app.asar/src/workspace.js:631:35)
    at atom-workspace.commandRegistry.add.core:save (/Applications/Atom.app/Contents/Resources/app.asar/src/register-default-commands.js:173:32)
    at CommandRegistry.module.exports.CommandRegistry.handleCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:260:29)
    at /Applications/Atom.app/Contents/Resources/app.asar/src/command-registry.js:3:61
    at KeymapManager.module.exports.KeymapManager.dispatchCommandEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:533:16)
    at KeymapManager.module.exports.KeymapManager.handleKeyboardEvent (/Applications/Atom.app/Contents/Resources/app.asar/node_modules/atom-keymap/lib/keymap-manager.js:356:22)
    at WindowEventHandler.module.exports.WindowEventHandler.handleDocumentKeydown (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:99:36)
    at HTMLDocument.<anonymous> (/Applications/Atom.app/Contents/Resources/app.asar/src/window-event-handler.js:3:61)
```

### Commands

```
     -0:19.3.0 emmet:insert-formatted-line-break-only (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:19.3.0 docblockr:parse-enter (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:19.3.0 editor:newline (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:12.7.0 core:move-up (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:11.9.0 core:move-left (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  3x -0:11.6.0 editor:move-to-beginning-of-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:10.3.0 editor:select-to-beginning-of-word (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:09.5.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:08.9.0 editor:move-to-end-of-screen-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:08.6.0 editor:select-to-first-character-of-line (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
  2x -0:08.0 core:backspace (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:07.1.0 vim-mode:activate-normal-mode (atom-text-editor.editor.vim-mode.is-focused.insert-mode)
     -0:06.0 core:save (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  3x -0:03.2.0 blur (atom-text-editor.editor.vim-mode.is-focused.normal-mode)
  2x -0:01.1.0 vim-mode:move-down (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
     -0:00.7.0 core:save (atom-text-editor.editor.vim-mode.normal-mode.is-focused)
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "vim-mode-plus"
    ]
  }
}
```

### Installed Packages

```coffee
# User
atom-jshint, v2.0.0
clipboard-plus, v0.5.1
docblock-format-helper, v0.3.0
docblockr, v0.7.3
docs-snippets, v0.8.0
emmet, v2.3.14
jshint, v1.8.3
linter, v1.10.0
vim-mode, v0.63.0
vim-mode-clipboard-plus, v0.1.0
vim-surround, v0.8.0

# Dev
No dev packages
```

**Comment by olsonpm** [comment]
FWIW I am getting this too.  I don't have the time to look into it unfortunately, which I do apologize about given this is a great open source package.

**Comment by workmanw** [comment]
I too am getting this issue. Restarting Atom seems to clear it up for a period of time. But I find myself restarting Atom 3-4 times a day. :(

**Comment by carmelolg** [comment]
+1
