### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by adityaghosh1987** [Joezo/atom-jshint#121]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.2.4
**System**: Microsoft Windows 10 Home Single Language
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v2.0.0
### Stack Trace

Uncaught Error: channel closed

```
At events.js:141

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:509:16)
    at AtomJsHint.module.exports.AtomJsHint.run (C:\Users\WittyParrot\.atom\packages\atom-jshint\lib\atom-jshint.js:105:21)
    at AtomJsHint.<anonymous> (C:\Users\WittyParrot\.atom\packages\atom-jshint\lib\atom-jshint.js:66:16)
    at Emitter.module.exports.Emitter.emit (C:\Users\WittyParrot\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\event-kit\lib\emitter.js:86:11)
    at C:\Users\WittyParrot\AppData\Local\atom\app-1.2.4\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1276:25
```
### Commands

```
     -2:44.8.0 core:paste (atom-text-editor.editor.is-focused)
  2x -2:44.4.0 core:save (atom-text-editor.editor.is-focused)
     -2:36.3.0 core:copy (atom-text-editor.editor.is-focused)
     -2:34.6.0 core:paste (atom-text-editor.editor.is-focused)
  4x -2:27.4.0 core:save (atom-text-editor.editor.is-focused.autocomplete-active)
     -1:37.7.0 find-and-replace:show (atom-text-editor.editor.is-focused)
     -1:10.5.0 editor:newline (atom-text-editor.editor.is-focused)
  3x -1:05.7.0 core:move-left (atom-text-editor.editor.is-focused)
  7x -0:59.1.0 core:backspace (atom-text-editor.editor.is-focused)
  7x -0:46.6.0 core:save (atom-text-editor.editor.is-focused)
     -0:30 core:paste (atom-text-editor.editor.is-focused)
     -0:27.1.0 core:copy (atom-text-editor.editor.is-focused)
     -0:25.5.0 core:paste (atom-text-editor.editor.is-focused)
     -0:17.7.0 core:move-left (atom-text-editor.editor.is-focused)
  3x -0:13.8.0 core:save (atom-text-editor.editor.is-focused)
     -0:03.2.0 editor:newline (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "themes": [
      "atom-dark-ui",
      "solarized-dark-syntax"
    ]
  }
}
```
### Installed Packages

``` coffee
# User
atom-jshint, v2.0.0
git-merge-conflicts, v0.0.2
pigments, v0.19.1

# Dev
No dev packages
```

**Comment by carmelolg** [comment]
+1

**Comment by gvanderest** [comment]
+1

**Comment by carmelolg** [comment]
I will become crazy!!

**Comment by sungwoncho** [comment]
Seeing this all of a sudden. Running atom 1.3.3 on OSX Yosemite. The plugin version I'm running is 2.0.0.

**Comment by ricardograca** [comment]
You should just use linter-jshint since this project is not maintained anymore.
