### ISSUE TITLE
Uncaught Error: channel closed

### ISSUE THREAD

**Issue by agudovitoria** [Joezo/atom-jshint#126]
[Enter steps to reproduce below:]
1. ...
2. ...

**Atom Version**: 1.8.0
**System**: Unknown Windows Version
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v2.0.0
### Stack Trace

Uncaught Error: channel closed

```
At events.js:141

Error: channel closed
    at ChildProcess.target.send (internal/child_process.js:509:16)
    at AtomJsHint.module.exports.AtomJsHint.run (C:\Users\iagudovi\.atom\packages\atom-jshint\lib\atom-jshint.js:105:21)
    at AtomJsHint.<anonymous> (C:\Users\iagudovi\.atom\packages\atom-jshint\lib\atom-jshint.js:66:16)
    at Function.module.exports.Emitter.simpleDispatch (C:\Users\iagudovi\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:25:14)
    at Emitter.module.exports.Emitter.emit (C:\Users\iagudovi\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\event-kit\lib\emitter.js:125:28)
    at C:\Users\iagudovi\AppData\Local\atom\app-1.8.0\resources\app.asar\node_modules\text-buffer\lib\text-buffer.js:1378:25
```
### Commands

```
     -1:13 editor:consolidate-selections (atom-text-editor.editor.is-focused)
     -1:13 core:cancel (atom-text-editor.editor.is-focused)
     -1:06.4.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -1:06.4.0 editor:newline (atom-text-editor.editor.is-focused)
     -1:04.4.0 core:move-left (atom-text-editor.editor.is-focused)
     -0:56.7.0 core:move-right (atom-text-editor.editor.is-focused)
     -0:55.2.0 docblockr:parse-enter (atom-text-editor.editor.is-focused)
     -0:55.2.0 editor:newline (atom-text-editor.editor.is-focused)
     -0:54.8.0 core:move-down (atom-text-editor.editor.is-focused)
  9x -0:54.4.0 editor:move-line-down (atom-text-editor.editor.is-focused)
     -0:52.6.0 editor:move-line-up (atom-text-editor.editor.is-focused)
     -0:49.9.0 atom-beautify:beautify-editor (atom-text-editor.editor.is-focused)
     -0:47.6.0 core:backspace (atom-text-editor.editor.is-focused)
  2x -0:46.9.0 core:save (atom-text-editor.editor.is-focused)
     -0:05.2.0 editor:delete-line (atom-text-editor.editor.is-focused)
     -0:04.7.0 core:save (atom-text-editor.editor.is-focused)
```
### Config

``` json
{
  "core": {
    "disabledPackages": [
      "git-time-machine",
      "tree-view-git-branch",
      "tree-view-git-projects",
      "tree-view-git-status",
      "minimap-git-diff",
      "todo-list",
      "todo",
      "todo-manager",
      "npm",
      "linter-jscs",
      "linter-package-json-validator",
      "linter-json-lint",
      "tree-view-git-modified",
      "optional-jshint"
    ],
    "projectHome": "C:\\Users\\iagudovi\\Desktop\\CODIGO"
  },
  "atom-jshint": {}
}
```
### Installed Packages

``` coffee
# User
angularjs, v0.3.4
atom-beautify, v0.29.9
atom-jshint, v2.0.0
atom-json-color, v0.4.2
atomic-chrome, v0.3.0
autocomplete-angular-material, v0.4.0
autoupdate-packages, v1.3.1
chary-tree-view, v0.2.3
docblockr, v0.7.3
emmet, v2.4.3
file-icons, v1.7.16
jshint, v1.8.5
linter, v1.11.14
linter-bootlint, v1.0.2
linter-htmlhint, v1.2.1
linter-sass-lint, v1.6.1
minimap, v4.24.7
minimap-pigments, v0.2.1
pretty-json, v1.4.1

# Dev
No dev packages
```

**Comment by abey-alex** [comment]
Facing the same issue.

**Comment by nabilfreeman** [comment]
@Joezo

**Comment by mattbdean** [comment]
A restart seems to fix the issue. Can anyone else verify?
