### ISSUE TITLE
Uncaught TypeError: Cannot read property 'getBuffer' of undefined

### ISSUE THREAD

**Issue by trideepgogoi** [Joezo/atom-jshint#65]
Uncaught TypeError: Cannot read property 'getBuffer' of undefined

**Atom Version**: 0.156.0
**System**: Mac OS X 10.9.5
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v1.5.0

### Steps To Reproduce

1. ...
2. ...

### Stack Trace

```
At /Users/tgogoi/.atom/packages/atom-jshint/lib/atom-jshint.js:58

TypeError: Cannot read property 'getBuffer' of undefined
  at AtomJsHint.module.exports.AtomJsHint.subscribeEditor (/Users/tgogoi/.atom/packages/atom-jshint/lib/atom-jshint.js:58:24)
  at AtomJsHint.<anonymous> (/Users/tgogoi/.atom/packages/atom-jshint/lib/atom-jshint.js:36:14)

```

/cc @atom/core

**Comment by Joezo** [comment]
This should be fixed in the current version
