### ISSUE TITLE
Failed to activate the atom-jshint package

### ISSUE THREAD

**Issue by mike** [Joezo/atom-jshint#88]
[Enter steps to reproduce below:]

1. Launch Atom

**Atom Version**: 0.191.0 :warning: **in 1.0 API Preview Mode** :warning:
**System**: Mac OS X 10.10.3
**Thrown From**: [atom-jshint](https://github.com/Joezo/atom-jshint) package, v1.5.0

### Stack Trace

Failed to activate the atom-jshint package

```
At Cannot read property 'on' of undefined

TypeError: Cannot read property 'on' of undefined
    at AtomJsHint.module.exports.Subscriber.subscribeWith (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/subscriber.js:25:23)
    at AtomJsHint.module.exports.Subscriber.subscribe (/Applications/Atom.app/Contents/Resources/app/node_modules/emissary/lib/subscriber.js:63:21)
    at new AtomJsHint (/Users/toru/.atom/packages/atom-jshint/lib/atom-jshint.js:20:10)
    at Object.module.exports.activate (/Users/toru/.atom/packages/atom-jshint/index.js:11:30)
    at Package.module.exports.Package.activateNow (/Applications/Atom.app/Contents/Resources/app/src/package.js:222:19)
    at /Applications/Atom.app/Contents/Resources/app/src/package.js:203:30
    at Package.module.exports.Package.measure (/Applications/Atom.app/Contents/Resources/app/src/package.js:147:15)
    at Package.module.exports.Package.activate (/Applications/Atom.app/Contents/Resources/app/src/package.js:195:14)
    at PackageManager.module.exports.PackageManager.activatePackage (/Applications/Atom.app/Contents/Resources/app/src/package-manager.js:434:21)
    at /Applications/Atom.app/Contents/Resources/app/src/package-manager.js:418:29
```

### Commands

```
```

### Config

```json
{
  "core": {
    "disabledPackages": [
      "metrics",
      "highlight-selected",
      "exception-reporting",
      "feedback",
      "less-autocompile",
      "terminal",
      "language-mustache",
      "language-go",
      "language-c",
      "language-clojure",
      "language-toml"
    ]
  },
  "atom-jshint": {
    "showErrorPanel": false
  }
}
```

### Installed Packages

```coffee
# User
atom-color-highlight, v3.0.8
atom-html-preview, v0.1.6
atom-jshint, v1.5.0
atom-prettify, v0.1.0
color-picker, v1.6.0
dash, v1.1.0
language-mako, v0.4.0
linter, v0.12.0
linter-csslint, v0.0.11
linter-jshint, v0.1.2
linter-pylint, v0.2.1
minimap, v4.7.6
project-manager, v1.15.5
project-palette-finder, v2.4.16

# Dev
No dev packages
```

**Comment by adi518** [comment]
I get a similar error: "At Cannot read property 'constructor' of undefined".

**Comment by Joezo** [comment]
I believe this is fixed in the latest version of this package. 2.0.0, please let me know.
