### ISSUE TITLE
Error when trying to lint JSX file

### ISSUE THREAD

**Issue by AfflatusX** [Joezo/atom-jshint#93]
got this error every time I try to lint:

[Enter steps to reproduce below:]

1. ...
2. ...

**Atom Version**: 0.196.9914978
**System**: Mac OS X 10.10.3
**Thrown From**: [jshint](https://github.com/sindresorhus/atom-jshint) package, v1.3.5

### Stack Trace

Uncaught Error: ENOENT: no such file or directory, uv_chdir

```
At /Applications/Nuclide.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/graceful-fs/polyfills.js:14

Error: ENOENT: no such file or directory, uv_chdir
  at Error (native)
  at process.chdir (/Applications/Nuclide.app/Contents/Resources/app/node_modules/babel-core/node_modules/regenerator/node_modules/commoner/node_modules/graceful-fs/polyfills.js:14:9)
  at lint (/Users/txie/.atom/packages/jshint/index.js:177:10)
  at delayed (/Applications/Nuclide.app/Contents/Resources/app/node_modules/babel-core/node_modules/lodash/index.js:7707:27)

```

### Commands

```
  2x -0:35.2.0 core:move-down (atom-text-editor.editor.mini)
     -0:33.3.0 core:move-up (atom-text-editor.editor.mini)
     -0:32.8.0 core:move-down (atom-text-editor.editor.mini)
     -0:32.4.0 core:confirm (atom-text-editor.editor.mini)
     -0:21.8.0 arsenal-click-to-symbol:activate (atom-text-editor.editor)
     -0:21.7.0 nuclide-quick-open:toggle-quick-open (atom-text-editor.editor)
     -0:19.3.0 core:backspace (atom-text-editor.editor.mini)
  7x -0:15.2.0 core:move-down (atom-text-editor.editor.mini)
  2x -0:12.8.0 core:move-up (atom-text-editor.editor.mini)
  3x -0:11.1.0 core:move-down (atom-text-editor.editor.mini)
     -0:10.5.0 core:move-up (atom-text-editor.editor.mini)
  8x -0:09.4.0 core:move-down (atom-text-editor.editor.mini)
  2x -0:05.4.0 core:move-up (atom-text-editor.editor.mini)
     -0:04.4.0 core:confirm (atom-text-editor.editor.mini)
     -0:02.6.0 arsenal-click-to-symbol:activate (atom-text-editor.editor.is-focused)
     -0:01.8.0 core:save (atom-text-editor.editor.is-focused)
```

### Config

```json
{
  "core": {
    "themes": [
      "seti-ui",
      "seti-syntax"
    ],
    "disabledPackages": [
      "incompatible-packages",
      "styleguide",
      "timecop",
      "metrics",
      "language-ocaml",
      "linter-eslint",
      "deprecation-cop",
      "autocomplete",
      "tree-view"
    ]
  },
  "jshint": {
    "supportLintingJsx": true
  }
}
```

### Installed Packages

```coffee
# User
atom-beautify, v0.26.4
autocomplete-css, v0.6.0
autocomplete-plus, v2.12.1
jshint, v1.3.5
react, v0.11.8
seti-syntax, v0.4.0
seti-ui, v0.7.1

# Dev
No dev packages
```

**Comment by Joezo** [comment]
This is actually an issue with http://github.com/sindresorhus/atom-jshint, not this package. I'd help if I could :(
